# Generated by Django 3.2.7 on 2023-05-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230531_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(max_length=50),
        ),
    ]
